/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/jTSIWTASQ7x
 */
import Project from "@/app/Project"
import { CardContent, Card } from "@/components/ui/card"
import { CarouselItem, CarouselContent, CarouselPrevious, CarouselNext, Carousel } from "@/components/ui/carousel"

export function CarouselCustom() {
  return (
    <Carousel className="w-full max-w-sm">
      <CarouselContent className="h-96">
      <CarouselItem>
      <Project
          imgsrc="/FireChat.png"
          alt="FireChat"
          projname="FireChat"
          projlink="https://firechat-tawny.vercel.app/"
          projinfo="
          Este é um projeto feito para uma vaga específica de Frontend onde tentei usar os requisitos solicitados na vaga para demonstrar minhas habilidades. É meu primeiro projeto utilizando Vue, Vuex, Vue Router e Firebase.
          o codigo para este projeto pode ser encontrado em github.com/duansydor/firechat/"
          technologies={
            [
              {
                id: 1,
                name: "Vue",
                width: "100%"
              },
              {
                id: 2,
                name: "Vuex",
                width: "100"
              },
              {
                id: 3,
                name: "Router",
                width: "40%"
              },
              {
                id: 4,
                name: "Firebase",
                width: "40%"
              },
            ]
          }
        />
        </CarouselItem>
        <CarouselItem>
        <Project
          imgsrc="/tarot.png"
          alt="Tarot"
          projname="Tarot"
          projlink="https://tarotreader-jet.vercel.app/"
          projinfo="
          Este WebApp gera cartas de Tarot aleatórias com seu respectivo significado, foi utilizado apenas HTML, Javscript e CSS e tambem Lottie para as animações"
          technologies={
            [
              {
                id: 1,
                name: "JavaScript",
                width: "70%"
              },
              {
                id: 2,
                name: "CSS",
                width: "38.5%"
              },
              {
                id: 3,
                name: "Lootie",
                width: "90%"
              }
            ]
          }
        />
        </CarouselItem>
        <CarouselItem>
        <Project
          imgsrc="/moldegenerator.png"
          alt="Projeto - gerador de moldes de letras"
          projname="Moldes de letras para E.V.A"
          projlink="https://gerarmoldes.vercel.app/"
          projinfo="
          Este é um projeto desenvolvido com a finalidade de facilitar a criação de moldes de letras na papelaria onde trabalho,
          para que posteriormente sejam impressas e utilizadas na criação de letras em E.V.A de forma rápida e simples."
          technologies={
            [
              {
                id: 1,
                name: "NextJS",
                width: "70%"
              },
              {
                id: 2,
                name: "SCSS",
                width: "38.5%"
              },
              {
                id: 3,
                name: "Figma",
                width: "90%"
              }
            ]
          }
        />
        </CarouselItem>
        <CarouselItem>
        <Project
          imgsrc="/duoicon.png"
          alt="DuolingoClone"
          projname="Duolingo Clone"
          projlink="https://duolingoclone-one.vercel.app/"
          projinfo="Este projeto(ainda em desenvolvimento) é uma tentativa de copiar a interface do duolingo para praticar algumas funções do tailwind e de css em geral.
          foi utilizado React com NextJS para algumas interações, como botões"
          technologies={
            [
              {
                id: 1,
                name: "React",
                width: "70%"
              },
              {
                id: 2,
                name: "TailwindCSS",
                width: "38.5%"
              },
            ]
          }
        />
        </CarouselItem>
      </CarouselContent>
      <CarouselPrevious />
      <CarouselNext />
    </Carousel>
  )
}
