/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/afCUyEMnXuc
 */
"use client"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import React, { useRef } from 'react';
import emailjs from '@emailjs/browser';

export function ContactForm() {
  const form = useRef();

  const sendEmail = (e:any) => {
    e.preventDefault();

    emailjs
      .sendForm('service_0ztp7av', 'template_s2kjost', form.current, {
        publicKey: '6Ctcx4RYZMtVHK3Vz',
      })
      .then(
        () => {
          console.log('SUCCESS!');
        },
        (error) => {
          console.log('FAILED...', error.text);
        },
      );
  };
  return (
    <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
      <form ref={form} onSubmit={sendEmail} className="w-full max-w-lg space-y-8">
        <div className="space-y-2">
          <h2 className="text-3xl font-bold">Mais informações?</h2>
          <p className="text-gray-500 dark:text-gray-400">Deixe sua mensagem abaixo :)</p>
        </div>
        <div className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="name">Name</Label>
            <Input name="user_name" id="name" placeholder="Enter your name" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="email">Email</Label>
            <Input name="user_email" id="email" placeholder="Enter your email" type="email" />
          </div>
          <div className="space-y-2">
            <Label  htmlFor="message">Message</Label>
            <Textarea name="message" className="min-h-[100px]" id="message" placeholder="Enter your message" />
          </div>
          <button className="bg-blue-900 rounded-lg p-2 text-gray-100"  type="submit">Send message</button>
        </div>
      </form>
      <div className="relative">
        <img
          alt="Contact Image"
          className="object-cover w-full h-full rounded-lg"
          height={400}
          src="/contact.svg"
          style={{
            aspectRatio: "500/400",
            objectFit: "cover",
          }}
          width={500}
        />
      </div>
    </div>
  )
}
