/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/afCUyEMnXuc
 */
"use client"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import React, { useRef } from 'react';
import emailjs from '@emailjs/browser';
import { Toaster, toast } from 'sonner'

<<<<<<< HEAD
export function ContactForm(props:any) {
  const form:any = useRef();
  const email_keys = props.email_keys
=======
export function ContactForm() {
  const form = useRef<HTMLFormElement>(null);
  const currentform = form.current as string | HTMLFormElement;
>>>>>>> d55515760f1803265ff42dec7a8dbd953a236083
  const sendEmail = (e:any) => {
    e.preventDefault();
    emailjs
<<<<<<< HEAD
      .sendForm(email_keys.service_id, email_keys.template_id, form.current, {
        publicKey: email_keys.public_key,
=======
      .sendForm('service_0ztp7av', 'template_s2kjost', currentform, {
        publicKey: '6Ctcx4RYZMtVHK3Vz',
>>>>>>> d55515760f1803265ff42dec7a8dbd953a236083
      })
      .then(
        () => {
          toast.success('Obrigado por sua mensagem! logo entrarei em contato :)')
        },
        (error) => {
          toast.error('Ocorreu um erro ao enviar o email'+error)
          
        },
      );
      form.current.reset()
  };
  return (
    <div  className="grid grid-cols-1 md:grid-cols-2 gap-8">
      <form ref={form} onSubmit={sendEmail} className="w-full max-w-lg space-y-8">
        <div className="space-y-2">
          <h2 className="text-3xl font-bold">Mais informações?</h2>
          <p className="text-gray-500 dark:text-gray-400">Deixe sua mensagem abaixo :)</p>
        </div>
        <div className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="name">Name</Label>
            <Input required name="user_name" id="name" placeholder="Enter your name" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="email">Email</Label>
            <Input required name="user_email" id="email" placeholder="Enter your email" type="email" />
          </div>
          <div className="space-y-2">
            <Label  htmlFor="message">Message</Label>
            <Textarea required name="message" className="min-h-[100px]" id="message" placeholder="Enter your message" />
          </div>
          <button className="bg-blue-900 rounded-lg p-2 text-gray-100"  type="submit">Send message</button>
        </div>
        
      </form>
      
      <div className="relative">
        <img
          alt="Contact Image"
          className="object-cover w-full h-full rounded-lg"
          height={400}
          src="/Contact.svg"
          style={{
            aspectRatio: "500/400",
            objectFit: "cover",
          }}
          width={500}
        />
      </div>
      <Toaster 
        richColors
        closeButton
        expand={true} 
        position="top-center"
      />
    </div>
  )
}
